---
- name: MAKE GROUP FOR SCRIPT
  group:
    name: "{{ group }}"

- name: MAKE USER FOR SCRIPT
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    create_home: no

- name: MAKE SCRIPT DIR
  file:
    path: "/opt"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0755'

- name: COPY SCRIPT IN SCRIPT`S HOME DIR
  copy:
    src: "otus.rb"
    dest: "{{ script_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0755'

- name: MAKE INIT unit-file
  template:
    src: "otus.service.j2"
    dest: "/etc/systemd/system/otus.service"
  notify: reload systemd

- name: ENABLING AND STARTING THE SERVICE
  systemd:
    name: "otus.service"
    state: started
    enabled: yes
    daemon_reload: yes

...