---

- name: Update APT Cache
  hosts: all
  become: yes
  gather_facts: true
  roles:
    - common

- name: Configuring NFS SRV
  hosts: all
  become: yes
  gather_facts: true
  roles:
    - otus_rb-deploy

...